name: ESLint

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.js'
      - 'eslint.config.js'
      - '.github/workflows/eslint.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.js'
      - 'eslint.config.js'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
